function sortByLabel(arr: { code: string; label: string }[]) {
  const [first, ...rest] = arr;
  const sorted = [...rest].sort((a, b) => a.label.localeCompare(b.label));
  return first.code === "unknown" ? [first, ...sorted] : sorted;
}

export const INDIAN_LANGUAGES = sortByLabel([
  { code: "unknown", label: "Auto-detect" },
  { code: "as-IN", label: "Assamese" },
  { code: "bn-IN", label: "Bengali" },
  { code: "en-IN", label: "English" },
  { code: "gu-IN", label: "Gujarati" },
  { code: "hi-IN", label: "Hindi" },
  { code: "kn-IN", label: "Kannada" },
  { code: "ml-IN", label: "Malayalam" },
  { code: "mr-IN", label: "Marathi" },
  { code: "or-IN", label: "Odia" },
  { code: "pa-IN", label: "Punjabi" },
  { code: "ta-IN", label: "Tamil" },
  { code: "te-IN", label: "Telugu" },
]);

export const GLOBAL_LANGUAGES = sortByLabel([
  { code: "unknown", label: "Auto-detect" },
  { code: "am", label: "Amharic" },
  { code: "ar", label: "Arabic" },
  { code: "as-IN", label: "Assamese" },
  { code: "bn-IN", label: "Bengali" },
  { code: "my", label: "Burmese" },
  { code: "zh", label: "Chinese" },
  { code: "nl", label: "Dutch" },
  { code: "en-IN", label: "English" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "gu-IN", label: "Gujarati" },
  { code: "ha", label: "Hausa" },
  { code: "hi-IN", label: "Hindi" },
  { code: "ig", label: "Igbo" },
  { code: "id", label: "Indonesian" },
  { code: "it", label: "Italian" },
  { code: "ja", label: "Japanese" },
  { code: "kn-IN", label: "Kannada" },
  { code: "km", label: "Khmer" },
  { code: "ko", label: "Korean" },
  { code: "lo", label: "Lao" },
  { code: "ml-IN", label: "Malayalam" },
  { code: "ms", label: "Malay" },
  { code: "mr-IN", label: "Marathi" },
  { code: "ne", label: "Nepali" },
  { code: "or-IN", label: "Odia" },
  { code: "pl", label: "Polish" },
  { code: "pt", label: "Portuguese" },
  { code: "pa-IN", label: "Punjabi" },
  { code: "ru", label: "Russian" },
  { code: "si", label: "Sinhala" },
  { code: "es", label: "Spanish" },
  { code: "sw", label: "Swahili" },
  { code: "sv", label: "Swedish" },
  { code: "ta-IN", label: "Tamil" },
  { code: "te-IN", label: "Telugu" },
  { code: "th", label: "Thai" },
  { code: "tr", label: "Turkish" },
  { code: "ur", label: "Urdu" },
  { code: "vi", label: "Vietnamese" },
  { code: "yo", label: "Yoruba" },
  { code: "zu", label: "Zulu" },
]);
